package constants

var (
	BiteChecked               = "bite_checked"
	CatFileChopLumpChecked    = "cat_file_chop_lump_checked"
	CatFileFlipChecked        = "cat_file_flip_checked"
	CatFileVowChecked         = "cat_file_vow_checked"
	DealChecked               = "deal_checked"
	DentChecked               = "dent_checked"
	FlapKickChecked           = "flap_kick_checked"
	FlipKickChecked           = "flip_kick_checked"
	FlopKickChecked           = "flop_kick_checked"
	JugDripChecked            = "jug_drip_checked"
	JugFileBaseChecked        = "jug_file_base_checked"
	JugFileIlkChecked         = "jug_file_ilk_checked"
	JugFileVowChecked         = "jug_file_vow_checked"
	PriceFeedsChecked         = "price_feeds_checked"
	TendChecked               = "tend_checked"
	VatFileDebtCeilingChecked = "vat_file_debt_ceiling_checked"
	VatFileIlkChecked         = "vat_file_ilk_checked"
	VatFluxChecked            = "vat_flux_checked"
	VatFoldChecked            = "vat_fold_checked"
	VatFrobChecked            = "vat_frob_checked"
	VatGrabChecked            = "vat_grab_checked"
	VatHealChecked            = "vat_heal_checked"
	VatInitChecked            = "vat_init_checked"
	VatMoveChecked            = "vat_move_checked"
	VatSlipChecked            = "vat_slip_checked"
	VowFessChecked            = "vow_fess_checked"
	VowFlogChecked            = "vow_flog_checked"
)
