package constants

const (
	BiteLabel               = "bite"
	CatFileChopLumpLabel    = "catFileChopLump"
	CatFileFlipLabel        = "catFileFlip"
	CatFilePitVowLabel      = "catFilePitVow"
	DealLabel               = "deal"
	DentLabel               = "dent"
	JugDripLabel            = "jugDrip"
	FlapKickLabel           = "flapKick"
	FlipKickLabel           = "flipKick"
	FlopKickLabel           = "flopKick"
	JugFileIlkLabel         = "jugFileIlk"
	JugFileRepoLabel        = "jugFileRepo"
	JugFileVowLabel         = "jugFileVow"
	PriceFeedLabel          = "priceFeed"
	TendLabel               = "tend"
	VatFileDebtCeilingLabel = "vatFileDebtCeiling"
	VatFileIlkLabel         = "vatFileIlk"
	VatFluxLabel            = "vatFlux"
	VatFoldLabel            = "vatFold"
	VatFrobLabel            = "vatFrob"
	VatGrabLabel            = "vatGrab"
	VatHealLabel            = "vatHeal"
	VatInitLabel            = "vatInit"
	VatMoveLabel            = "vatMove"
	VatSlipLabel            = "vatSlip"
	VatTuneLabel            = "vatTune"
	VowFessLabel            = "vowFess"
	VowFlogLabel            = "vowFlog"
)
