package constants

const (
	BiteLabel               = "bite"
	CatFileChopLumpLabel    = "catFileChopLump"
	CatFileFlipLabel        = "catFileFlip"
	CatFileVowLabel         = "catFileVow"
	DealLabel               = "deal"
	DentLabel               = "dent"
	FlapKickLabel           = "flapKick"
	FlipKickLabel           = "flipKick"
	FlopKickLabel           = "flopKick"
	JugDripLabel            = "jugDrip"
	JugFileBaseLabel        = "jugFileBase"
	JugFileIlkLabel         = "jugFileIlk"
	JugFileVowLabel         = "jugFileVow"
	PipLogValueLabel        = "pipLogValue"
	TendLabel               = "tend"
	VatFileDebtCeilingLabel = "vatFileDebtCeiling"
	VatFileIlkLabel         = "vatFileIlk"
	VatFluxLabel            = "vatFlux"
	VatFoldLabel            = "vatFold"
	VatFrobLabel            = "vatFrob"
	VatGrabLabel            = "vatGrab"
	VatHealLabel            = "vatHeal"
	VatInitLabel            = "vatInit"
	VatMoveLabel            = "vatMove"
	VatSlipLabel            = "vatSlip"
	VowFessLabel            = "vowFess"
	VowFlogLabel            = "vowFlog"
)
