package constants

func GetBiteSignature() string               { return GetEventTopicZero(biteMethod()) }
func GetCatFileChopLumpSignature() string    { return GetLogNoteTopicZero(catFileChopLumpMethod()) }
func GetCatFileFlipSignature() string        { return GetLogNoteTopicZero(catFileFlipMethod()) }
func GetCatFilePitVowSignature() string      { return GetLogNoteTopicZero(catFilePitVowMethod()) }
func GetDealSignature() string               { return GetLogNoteTopicZero(dealMethod()) }
func GetDentFunctionSignature() string       { return GetLogNoteTopicZero(dentMethod()) }
func GetFlapKickSignature() string           { return GetEventTopicZero(flapKickMethod()) }
func GetFlipKickSignature() string           { return GetEventTopicZero(flipKickMethod()) }
func GetFlopKickSignature() string           { return GetEventTopicZero(flopKickMethod()) }
func GetJugDripSignature() string            { return GetLogNoteTopicZero(jugDripMethod()) }
func GetJugFileIlkSignature() string         { return GetLogNoteTopicZero(jugFileIlkMethod()) }
func GetJugFileRepoSignature() string        { return GetLogNoteTopicZero(jugFileRepoMethod()) }
func GetJugFileVowSignature() string         { return GetLogNoteTopicZero(jugFileVowMethod()) }
func GetLogValueSignature() string           { return GetEventTopicZero(logValueMethod()) }
func GetTendFunctionSignature() string       { return GetLogNoteTopicZero(tendMethod()) }
func GetVatFileDebtCeilingSignature() string { return GetLogNoteTopicZero(vatFileDebtCeilingMethod()) }
func GetVatFileIlkSignature() string         { return GetLogNoteTopicZero(vatFileIlkMethod()) }
func GetVatFluxSignature() string            { return GetLogNoteTopicZero(vatFluxMethod()) }
func GetVatFoldSignature() string            { return GetLogNoteTopicZero(vatFoldMethod()) }
func GetVatFrobSignature() string            { return GetLogNoteTopicZero(vatFrobMethod()) }
func GetVatGrabSignature() string            { return GetLogNoteTopicZero(vatGrabMethod()) }
func GetVatHealSignature() string            { return GetLogNoteTopicZero(vatHealMethod()) }
func GetVatInitSignature() string            { return GetLogNoteTopicZero(vatInitMethod()) }
func GetVatMoveSignature() string            { return GetLogNoteTopicZero(vatMoveMethod()) }
func GetVatSlipSignature() string            { return GetLogNoteTopicZero(vatSlipMethod()) }
func GetVatTuneSignature() string            { return GetLogNoteTopicZero(vatTuneMethod()) }
func GetVowFessSignature() string            { return GetLogNoteTopicZero(vowFessMethod()) }
func GetVowFlogSignature() string            { return GetLogNoteTopicZero(vowFlogMethod()) }
