package constants

func GetBiteSignature() string               { return GetEventTopicZero(biteMethod()) }
func GetCatFileChopLumpSignature() string    { return GetLogNoteTopicZero(catFileChopLumpMethod()) }
func GetCatFileFlipSignature() string        { return GetLogNoteTopicZero(catFileFlipMethod()) }
func GetCatFilePitVowSignature() string      { return GetLogNoteTopicZero(catFilePitVowMethod()) }
func GetDealSignature() string               { return GetLogNoteTopicZero(dealMethod()) }
func GetDentFunctionSignature() string       { return GetLogNoteTopicZero(dentMethod()) }
func GetDripDripSignature() string           { return GetLogNoteTopicZero(dripDripMethod()) }
func GetDripFileIlkSignature() string        { return GetLogNoteTopicZero(dripFileIlkMethod()) }
func GetDripFileRepoSignature() string       { return GetLogNoteTopicZero(dripFileRepoMethod()) }
func GetDripFileVowSignature() string        { return GetLogNoteTopicZero(dripFileVowMethod()) }
func GetFlapKickSignature() string           { return GetEventTopicZero(flapKickMethod()) }
func GetFlipKickSignature() string           { return GetEventTopicZero(flipKickMethod()) }
func GetFlopKickSignature() string           { return GetEventTopicZero(flopKickMethod()) }
func GetVatFrobSignature() string            { return GetLogNoteTopicZero(vatFrobMethod()) }
func GetLogValueSignature() string           { return GetEventTopicZero(logValueMethod()) }
func GetPitFileDebtCeilingSignature() string { return GetLogNoteTopicZero(pitFileDebtCeilingMethod()) }
func GetPitFileIlkSignature() string         { return GetLogNoteTopicZero(pitFileIlkMethod()) }
func GetTendFunctionSignature() string       { return GetLogNoteTopicZero(tendMethod()) }
func GetVatFluxSignature() string            { return GetLogNoteTopicZero(vatFluxMethod()) }
func GetVatFoldSignature() string            { return GetLogNoteTopicZero(vatFoldMethod()) }
func GetVatGrabSignature() string            { return GetLogNoteTopicZero(vatGrabMethod()) }
func GetVatHealSignature() string            { return GetLogNoteTopicZero(vatHealMethod()) }
func GetVatInitSignature() string            { return GetLogNoteTopicZero(vatInitMethod()) }
func GetVatMoveSignature() string            { return GetLogNoteTopicZero(vatMoveMethod()) }
func GetVatSlipSignature() string            { return GetLogNoteTopicZero(vatSlipMethod()) }
func GetVatTollSignature() string            { return GetLogNoteTopicZero(vatTollMethod()) }
func GetVatTuneSignature() string            { return GetLogNoteTopicZero(vatTuneMethod()) }
func GetVowFlogSignature() string            { return GetLogNoteTopicZero(vowFlogMethod()) }
