#!/usr/bin/env bash
# Provide me with a postgres database name, and I will:
# - Drop the database
# - Recreate the database
# - Run the vulcanizedb migration

if [ "$1" = "" ]; then
    echo "Provide a database name to reset"
    exit 1
fi

db=$1
dir=$(basename "$(pwd)")
if [ $dir != "mcd_transformers" ]
then
  echo "Run me from the mcd_transformers root dir"
  exit 1
fi

psql -c "DROP DATABASE $db" postgres
if [ $? -eq 0 ]; then
    psql -c "CREATE DATABASE $db WITH OWNER vulcanize" postgres
    make migrate NAME=$db
else
    echo "Couldnt drop the database. Are you connected? Does it exist?"
fi
