on:
  push:
    branches:
      - prod

name: Deploy to AWS Prod

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: prod
      AWS_REGION: eu-west-1
      DOCKER_ORG: makerdao
      MCD_EXECUTE_NAME: vdb-mcd-execute
      BACKFILL_STORAGE_NAME: vdb-backfill-storage
      BACKFILL_EVENTS_NAME: vdb-backfill-events
      EXTRACT_DIFFS_NAME: vdb-extract-diffs
      CLUSTER_NAME: vdb-cluster-prod
      PROD_NETWORK_CONFIG: awsvpcConfiguration={subnets=[${{ secrets.PROD_TASK_SUBNETS }}],securityGroups=[${{ secrets.PROD_TASK_SGS }}],assignPublicIp=${{ secrets.PROD_TASK_PUBLIC_IP }}}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract commit hash
      id: vars
      shell: bash
      run: |
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Build, tag, and push images to Docker Registry
      id: build-image
      env:
        SHA_TAG: ${{ steps.vars.outputs.sha_short }}
        LATEST_TAG: latest
        BRANCH_TAG: develop
      run: |
        # Build a docker container and
        # push it to Docker repo so that it can
        # be deployed to ECS.
        docker build -f dockerfiles/extract_diffs/Dockerfile \
                     -t $DOCKER_ORG/$EXTRACT_DIFFS_NAME:$SHA_TAG \
                     -t $DOCKER_ORG/$EXTRACT_DIFFS_NAME:$LATEST_TAG \
                     -t $DOCKER_ORG/$EXTRACT_DIFFS_NAME:$BRANCH_TAG \
                     .
        docker build -f dockerfiles/backfill_storage/Dockerfile \
                     -t $DOCKER_ORG/$BACKFILL_STORAGE_NAME:$SHA_TAG \
                     -t $DOCKER_ORG/$BACKFILL_STORAGE_NAME:$LATEST_TAG \
                     -t $DOCKER_ORG/$BACKFILL_STORAGE_NAME:$BRANCH_TAG \
                     .
        docker build -f dockerfiles/backfill_events/Dockerfile \
                     -t $DOCKER_ORG/$BACKFILL_EVENTS_NAME:$SHA_TAG \
                     -t $DOCKER_ORG/$BACKFILL_EVENTS_NAME:$LATEST_TAG \
                     -t $DOCKER_ORG/$BACKFILL_EVENTS_NAME:$BRANCH_TAG \
                     .
        docker build -f dockerfiles/execute/Dockerfile \
                     -t $DOCKER_ORG/$MCD_EXECUTE_NAME:$SHA_TAG \
                     -t $DOCKER_ORG/$MCD_EXECUTE_NAME:$LATEST_TAG \
                     -t $DOCKER_ORG/$MCD_EXECUTE_NAME:$BRANCH_TAG \
                     .
        docker push $DOCKER_ORG/$EXTRACT_DIFFS_NAME --all-tags
        docker push $DOCKER_ORG/$BACKFILL_STORAGE_NAME --all-tags
        docker push $DOCKER_ORG/$BACKFILL_EVENTS_NAME --all-tags
        docker push $DOCKER_ORG/$MCD_EXECUTE_NAME --all-tags

    - name: Run ECS Tasks with latest Docker image
      id: run-tasks
      run: |
        aws ecs run-task \
          --cluster $CLUSTER_NAME \
          --launch-type FARGATE \
          --task-definition $BACKFILL_EVENTS_NAME-$ENVIRONMENT \
          --network-configuration $PROD_NETWORK_CONFIG \
          --region $AWS_REGION

        aws ecs run-task \
          --cluster $CLUSTER_NAME \
          --launch-type FARGATE \
          --task-definition $BACKFILL_STORAGE_NAME-$ENVIRONMENT \
          --network-configuration $PROD_NETWORK_CONFIG \
          --region $AWS_REGION

    - name: Update ECS service with latest Docker image
      id: service-update
      run: |
        aws ecs update-service --cluster $CLUSTER_NAME --service ${{ env.$MCD_EXECUTE_NAME }}-$ENVIRONMENT --force-new-deployment --region $AWS_REGION
        aws ecs update-service --cluster $CLUSTER_NAME --service ${{ env.$EXTRACT_DIFFS_NAME }}-eu-$ENVIRONMENT --force-new-deployment --region $AWS_REGION
        aws ecs update-service --cluster $CLUSTER_NAME --service ${{ env.$EXTRACT_DIFFS_NAME }}-us-$ENVIRONMENT --force-new-deployment --region $AWS_REGION

    - name: Wait for all services to become stable
      uses: oryanmoshe/ecs-wait-action@v1.3
      with:
        ecs-cluster: ${{ env.CLUSTER_NAME }}
        ecs-services: '["${{ env.$MCD_EXECUTE_NAME }}-$ENVIRONMENT", "${{ env.$EXTRACT_DIFFS_NAME }}-eu-$ENVIRONMENT", "${{ env.$EXTRACT_DIFFS_NAME }}-us-$ENVIRONMENT"]'

    - name: Create Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      with:
        environment: prod
        version_prefix: vdb-mcd-transformers
