name: TestExecute

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Execute Image
        run: |
          docker build . -f dockerfiles/execute/Dockerfile

  
