name: TestVDBCommands

on: push

jobs:
  test-execute:
    runs-on: ubuntu-latest
    name: Test Execute Image
    steps:
      -
        name: Checkout repo
        uses: actions/checkout@v2
      -
        name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      -
        name: Build execute image
        uses: docker/build-push-action@v2
        with:
          file: ./dockerfiles/execute/Dockerfile
          push: false
          tags: makerdao/execute:gh_actions_test_version
      -
        name: Run the execute container
        env:
          CLIENT_IPCPATH: ${{ secrets.CLIENT_IPCPATH }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        run: |
          ./.github/workflows/check_vdb_command makerdao/execute:gh_actions_test_version --client_ipcpath $CLIENT_IPCPATH --database_user $DATABASE_USER --database_password $DATABASE_PASSWORD --database_name $DATABASE_NAME

    services:
      postgres:
        image: postgres:11.6
        env:
          POSTGRES_USER: ${{ secrets.DATABASE_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DATABASE_NAME }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
  
  test-extract:
    runs-on: ubuntu-latest
    name: Test Extract Diffs Image
    steps:
      -
       name: Checkout repo
       uses: actions/checkout@v2
      -
       name: Setup Python
       uses: actions/setup-python@v2
       with:
        python-version: 3.7
      -
       name: Build extract diffs image
       uses: docker/build-push-action@v2
       with:
          file: ./dockerfiles/extract_diffs/Dockerfile
          push: false
          tags: makerdao/extract_diffs:gh_actions_test_version
      -
       name: Run the extract diffs container
       env:
        CLIENT_WSSPATH: ${{ secrets.CLIENT_WSSPATH }}
        DATABASE_USER: ${{ secrets.DATABASE_USER }}
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        DATABASE_NAME: ${{ secrets.DATABASE_NAME }} 
       run: |
         ./.github/workflows/check_vdb_command makerdao/extract_diffs:gh_actions_test_version --storagediffs_source geth --client_ipcpath $CLIENT_WSSPATH --database_user $DATABASE_USER --database_password $DATABASE_PASSWORD --database_name $DATABASE_NAME

    services:
      postgres:
        image: postgres:11.6
        env:
          POSTGRES_USER: ${{ secrets.DATABASE_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DATABASE_NAME }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
