name: TestExecute

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Execute Image
    steps:
      -
        name: Checkout repo
        uses: actions/checkout@v2
      -
        name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      -
        name: Build execute image
        uses: docker/build-push-action@v2
        with:
          file: ./dockerfiles/execute/Dockerfile
          push: false
          tags: makerdao/execute:latest
      -
        name: Run the docker container
        env:
          CLIENT_IPCPATH: ${{ secrets.CLIENT_IPCPATH }}
        run: |
          ./.github/workflows/check_execute makerdao/execute:latest --client_ipcpath $CLIENT_IPCPATH

    services:
      postgres:
        image: postgres:11.6
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
  
